# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=embed_video.fields.EmbedVideoField(max_length=500),
        ),
    ]
